name: Epic
description: "Use this template to create an EPIC for the project."
title: "🏔️ EPIC: "
labels: []
projects: ["swissredcross/13"]
assignees: []
body:
  - type: input
    id: ticketnumber
    attributes:
      label: "📧 Context"
      description: "Ticket Number from Zendesk"
      value: "[resolves/fixes 🎟️ #TICKETNUMBER](https://srkcrs.zendesk.com/agent/tickets/TICKETNUMBER)"
    validations:
      required: false
  - type: textarea
    id: user-story
    attributes:
      label: "✍️ User Story"
      description: "As a [user role], I want to [user action] so that [user benefit]."
      value: |
        **As a** role
        **I want to** action
        **So that** benefit
    validations:
      required: true
