name: Epic
description: "Use this template to create an EPIC for the project."
title: "🏔️ EPIC: "
labels: []
projects: ["swissredcross/13"]
assignees: []
body:
  - type: input
    id: ticketnumber
    attributes:
      label: "Zendesk Ticket Number"
      description: "Ticket Number from Zendesk"
      value: "[resolves/fixes 🎟️ #TICKETNUMBER](https://srkcrs.zendesk.com/agent/tickets/TICKETNUMBER)"
    validations:
      required: false
  - type: markdown
    attributes:
      value: "# ✍️ User Story"
  - type: input
    id: user-role
    attributes:
      label: "As a"
      description: 'user role, e.g., "volunteer" without "As a"'
      placeholder: "user"
    validations:
      required: true
  - type: input
    id: user-action
    attributes:
      label: "I want to"
      description: 'user action, e.g., "a Call To Action for donations" without "I want to"'
      placeholder: "a Call To Action for donations"
    validations:
      required: true
  - type: input
    id: user-benefit
    attributes:
      label: "So that"
      description: 'user benefit, e.g., "I can quickly make a donation" without "So that"'
      placeholder: "I can quickly make a donation"
    validations:
      required: true
