name: Task
description: "Use this template to add a Task to the project."
title: "task: "
labels: []
projects: ["swissredcross/13"]
assignees: []
body:
  - type: input
    id: ticketnumber
    attributes:
      label: "📧 Context"
      description: "Ticket Number from Zendesk"
      value: "[resolves/fixes 🎟️ #TICKETNUMBER](https://srkcrs.zendesk.com/agent/tickets/TICKETNUMBER)"
    validations:
      required: false
  - type: textarea
    id: user-story
    attributes:
      label: "✍️ User Story"
      description: "As a [user role], I want to [user action] so that [user benefit]."
      value: |
        **As a** role
        **I want to** action
        **So that** benefit
    validations:
      required: true
  - type: textarea
    id: requirements
    attributes:
      label: "Requirements"
      description: "Provide clear and actionable requirements for the task."
      value: |
        - [ ] Requirement 1
        - [ ] Requirement 2
    validations:
      required: true
  - type: textarea
    id: links
    attributes:
      label: "Supporting Links"
      description: "Provide links to design, documentation, or other relevant resources."
      value: |
        - [Design Figma](figma_url)
        - [Documentation / Spec](doc_url)
    validations:
      required: false
