name: Task
description: 'Use this template to add a Task to the project.'
title: ''
labels: []
projects: ['swissredcross/13']
assignees: []
body:
    - type: input
      id: ticketnumber
      attributes:
          label: 'Zendesk Ticket Number'
          description: 'Ticket Number from Zendesk'
          placeholder: '12345'
      validations:
          required: false
    - type: input
      id: user-role
      attributes:
          label: 'User Story Role (As a ...)'
          description: 'user role, e.g., "volunteer" without "As a"'
          placeholder: 'user'
      validations:
          required: true
    - type: input
      id: user-action
      attributes:
          label: 'User Story Action (I want ...)'
          description: 'user action, e.g., "a Call To Action for donations" without "I want to"'
          placeholder: 'a Call To Action for donations'
      validations:
          required: true
    - type: input
      id: user-benefit
      attributes:
          label: 'User Story benefit (So that ...)'
          description: 'user benefit, e.g., "I can quickly make a donation" without "So that"'
          placeholder: 'I can quickly make a donation'
      validations:
          required: true
    - type: textarea
      id: requirements
      attributes:
          label: 'Requirements'
          description: 'Provide clear and actionable requirements for the task.'
          placeholder: |
              - [ ] Requirement 1
              - [ ] Requirement 2
      validations:
          required: true
    - type: textarea
      id: links
      attributes:
          label: 'Supporting Links'
          description: 'Provide links to design, documentation, or other relevant resources.'
          placeholder: |
              - [Design Figma](figma_url)
              - [Documentation / Spec](doc_url)
      validations:
          required: false
    - type: markdown
      attributes:
          value: |
              # 📧 Context (Original ticket)

              [resolves/fixes 🎟️ #{{ ticketnumber }}](https://srkcrs.zendesk.com/agent/tickets/{{ ticketnumber }})

              # ✍️ User Story

              **As a** {{ user-role }},
              **I want to** {{ user-action }},
              **so that** {{ user-benefit }}.

              ---

              ## 👩‍💻 Requirements

              {{ requirements }}

              ## 🔗 Supporting Links

              {{ links }}
